# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/meh/.dotfiles/.oh-my-zsh

# Locale to es_ES.UTF-8
. $ZSH/config/locale.meh

#ZSH theme
ZSH_THEME="meh"

# Plugins plugins=(git)
. $ZSH/oh-my-zsh.sh

# SSH KEYS
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Alias
. $ZSH/config/alias.meh

